language: elixir
cache:
  directories:
    - deps
    - _build
matrix:
  include:
    - elixir: 1.4.2
      otp_release: 19.3
    - elixir: 1.4.2
      otp_release: 19.0
    - elixir: 1.3.2
      otp_release: 18.3
    - elixir: 1.3.2
      otp_release: 19.0
env:
  global:
    - MIX_ENV=test
before_install:
script:
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
